### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Ishannaik** [edenizk/udemyRemainingTimerExtention#4]
No items found, be sure that sections are opened
I'm getting this message the sections are opening though
![image](https://github.com/edenizk/udemyRemainingTimerExtention/assets/11766476/467ca018-9981-4eff-9274-27d3c5dcb92b)

**Comment by edenizk** [comment]
Hi,
I will take a look thank you for letting me know :)

**Comment by edenizk** [comment]
Now it should be working again 🙂
Please take a look, and if it's working you can close the task

**Comment by Ishannaik** [comment]
Thank you for your help. I've been using this extension for about a year, and it's been really useful for me. Everything seems to be working fine now
